---
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    enabled: no
    gpgcheck: no
  tags: epel

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
    disablerepo: "epel"
  with_items: "{{ packages }}"
  tags: packages

- name: Install EPEL required packages
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "epel"
  with_items: "{{ epelpackages }}"
  tags: epelpackages

- name: Install pip required packages
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value.version | default(omit) }}"
  with_dict: "{{ pippackages }}"
  tags: pip
